#!/usr/bin/env python3

"""build

Usage:
  build [--out=<dir>] [--root=<url>]
  build (-h | --help)

Options:
  -h --help       Show this screen.
  --out=<dir>     Directory to generate site in [default: _site]
  --root=<url>    Root of the website [default: https://www.lookwhattheshoggothdraggedin.com/]
"""

import jinja2
import os

from distutils import dir_util
from docopt import docopt

args = docopt(__doc__)
OUT_DIR = args["--out"]
BASE_HREF = args["--root"]

JINJA2_ENV = jinja2.Environment(loader=jinja2.FileSystemLoader("_templates"))

TOPIC_NAMES = {
    "gm-advice": "GM Advice",
    "mechanics": "Mechanics",
    "review": "Review",
}

SYSTEM_NAMES = {
    "call-of-cthulhu": "Call of Cthulhu",
    "troika": "Troika!",
}

PLACEHOLDER_POSTS = [
    {
        "slug": "diegetic-character-advancement",
        "title": "Diegetic character advancement",
        "excerpt": "Characters get better over time, whether that be by hitting milestones or by gathering experience points.  But when they reach an advancement point, make it feel more meaningful by giving a justification in the fiction for the bonuses they get.",
        "day": 12,
        "month": "Feb",
        "year": 2021,
        "topic": "gm-advice",
    },
    {
        "slug": "first-impressions-of-troika",
        "title": "First impressions of Troika!",
        "excerpt": "words words words",
        "day": 7,
        "month": "Jan",
        "year": 2021,
        "system": "troika",
        "topic": "review",
    },
    {
        "slug": "dice-rolls-in-call-of-cthulhu",
        "title": "Dice rolls in Call of Cthulhu",
        "excerpt": "words words words",
        "day": 28,
        "month": "Dec",
        "year": 2020,
        "system": "call-of-cthulhu",
        "topic": "mechanics",
    },
]

YEARS = list(set(post["year"] for post in PLACEHOLDER_POSTS))

dir_util.copy_tree("static", OUT_DIR)
dir_util.mkpath(os.path.join(OUT_DIR, "topic"))
dir_util.mkpath(os.path.join(OUT_DIR, "system"))
dir_util.mkpath(os.path.join(OUT_DIR, "archive"))

with open(os.path.join(OUT_DIR, "index.html"), "w") as f:
    rendered = JINJA2_ENV.get_template("index.html").render(
        permalink = f"{BASE_HREF}/index.html",
        title = "Recent Posts",
        base_href = BASE_HREF,
        topic_names = TOPIC_NAMES,
        system_names = SYSTEM_NAMES,
        posts = PLACEHOLDER_POSTS,
        link_to_all_posts = True,
    )
    print(rendered, file=f)

with open(os.path.join(OUT_DIR, "all.html"), "w") as f:
    rendered = JINJA2_ENV.get_template("archive.html").render(
        permalink = f"{BASE_HREF}/all.html",
        title = "All Posts",
        base_href = BASE_HREF,
        topic_names = TOPIC_NAMES,
        system_names = SYSTEM_NAMES,
        posts = PLACEHOLDER_POSTS,
        link_to_all_posts = False,
    )
    print(rendered, file=f)

for slug, name in TOPIC_NAMES.items():
    with open(os.path.join(OUT_DIR, f"topic/{slug}.html"), "w") as f:
        rendered = JINJA2_ENV.get_template("archive.html").render(
            permalink = f"{BASE_HREF}/topic/{slug}.html",
            title = name,
            base_href = BASE_HREF,
            topic_names = TOPIC_NAMES,
            system_names = SYSTEM_NAMES,
            posts = [post for post in PLACEHOLDER_POSTS if post.get("topic") == slug],
            link_to_all_posts = True,
        )
        print(rendered, file=f)

for slug, name in SYSTEM_NAMES.items():
    with open(os.path.join(OUT_DIR, f"system/{slug}.html"), "w") as f:
        rendered = JINJA2_ENV.get_template("archive.html").render(
            permalink = f"{BASE_HREF}/system/{slug}.html",
            title = name,
            base_href = BASE_HREF,
            topic_names = TOPIC_NAMES,
            system_names = SYSTEM_NAMES,
            posts = [post for post in PLACEHOLDER_POSTS if post.get("system") == slug],
            link_to_all_posts = True,
        )
        print(rendered, file=f)

for year in YEARS:
    with open(os.path.join(OUT_DIR, f"archive/{year}.html"), "w") as f:
        rendered = JINJA2_ENV.get_template("archive.html").render(
            permalink = f"{BASE_HREF}/archive/{year}.html",
            title = year,
            base_href = BASE_HREF,
            topic_names = TOPIC_NAMES,
            system_names = SYSTEM_NAMES,
            posts = [post for post in PLACEHOLDER_POSTS if post.get("year") == year],
            link_to_all_posts = True,
        )
        print(rendered, file=f)
