resource_types:
  - name: rsync-resource
    type: docker-image
    source:
      repository: registry.barrucadu.dev/rsync-resource
      username: registry
      password: ((docker-registry-password))

resources:
  - name: nix-image
    type: registry-image
    source:
      repository: mirror.gcr.io/nixos/nix
  - name: www-git
    type: git
    source:
      uri: https://github.com/barrucadu/lookwhattheshoggothdraggedin.com.git
  - name: www-rsync
    type: rsync-resource
    source:
      server: carcosa.barrucadu.co.uk
      remote_dir: /persist/srv/http/lookwhattheshoggothdraggedin.com/www
      private_key: ((carcosa-ssh-private-key))

jobs:
  - name: update-pipeline
    plan:
      - get: www-git
        trigger: true
      - set_pipeline: www-lookwhattheshoggothdraggedin-com
        file: www-git/concourse/pipeline.yml

  - name: build-and-deploy
    serial: true
    plan:
      - get: nix-image
      - get: www-git
        trigger: true
      - task: build-site
        image: nix-image
        params:
          OUT_DIR: www
        config:
          platform: linux
          inputs:
            - name: www-git
          outputs:
            - name: site
          run:
            dir: www-git
            path: sh
            args:
              - -cex
              - |
                nix --extra-experimental-features "nix-command flakes" develop --command bash -c "./build --out=../site/${OUT_DIR}"
      - put: www-rsync
        params:
          path: site/www
          rsync_args:
            - --delete
